const mongoose = require("mongoose");
const { Schema } = mongoose;

const RequerimientosPlaneacion = new Schema({
    item: { type: String },
    folio: { type: String },
    sucursal: { type: String },
    semana: { type: String },
    acumulado: { type: String },
    acumuladoMaterial: { type: String },
    requerimiento: {
        semana: { type: String },
        producto: { type: String },
        nombreProducto: { type: String },
        numeroInterno: { type: String },
        um: { type: String },
        ov: { type: String },
        almacenProductoTerminado: { type: String },
        nombreProveedor: { type: String },
        ordenVenta: { type: Array, default: [] },
        totalProducir: { type: String },
        cliente: { type: String },
        nombreCliente: { type: String }
    },
    planeacion: {
        numeroMolde: { type: String },
        numeroCavidades: { type: String },
        opcionesMaquinaria: { type: Array, default: [] }
    },
    bom: {
        material: { type: String },
        idMaterial: { type: String },
        folioMaterial: { type: String },
        precioMaterial: { type: String },
        umMaterial: { type: String },
        molido: { type: String },
        pesoPieza: { type: String },
        pesoColada: { type: String },
        kgMaterial: { type: String },
        pigmento: { type: String },
        idPigmento: { type: String },
        folioPigmento: { type: String },
        precioPigmento: { type: String },
        umPigmento: { type: String },
        aplicacion: { type: String },
        pigMb: { type: String },
        materialxTurno: { type: String },
        merma: { type: String },
        empaque: { type: String },
        idEmpaque: { type: String },
        folioEmpaque: { type: String },
        precioEmpaque: { type: String },
        umEmpaque: { type: String },
        bolsasCajasUtilizar: { type: String },
        notas: { type: String },
        elaboro: { type: String },
    },
    datosRequisicion: {
        material: { type: String },
        kgMaterial: { type: String },
        almacenMP: { type: String },
        cantidadSugerida: { type: String },
        cantidadPedir: { type: String },

        pigmentoMB: { type: String },
        kgPigMB: { type: String },
        MbAlmacen: { type: String },
        cantidadSugeridaMB: { type: String },
        cantidadPedirMB: { type: String },

        empaque: { type: String },
        empaquesNecesarios: { type: String },
        empaquesAlmacen: { type: String },
        cantidadSugeridaEmpaques: { type: String },
        cantidadPedirEmpaques: { type: String }
    },
    programa: {
        fechaInicio: { type: String },
        lunesT1: { type: String },
        estadoLT1: { type: String },
        lunesT2: { type: String },
        estadoLT2: { type: String },
        martesT1: { type: String },
        estadoMT1: { type: String },
        martesT2: { type: String },
        estadoMT2: { type: String },
        miercolesT1: { type: String },
        estadoMIT1: { type: String },
        miercolesT2: { type: String },
        estadoMIT2: { type: String },
        juevesT1: { type: String },
        estadoJT1: { type: String },
        juevesT2: { type: String },
        estadoJT2: { type: String },
        viernesT1: { type: String },
        estadoVT1: { type: String },
        viernesT2: { type: String },
        estadoVT2: { type: String },
        sabadoT1: { type: String },
        estadoST1: { type: String },
    },
    resultados: { type: Array, default: [] },
    materiaPrima: { type: Array, default: [] },
    observaciones: { type: String },
    estado: { type: String }
}, {
    timestamps: true
});

module.exports = mongoose.model("RequerimientosPlaneacion", RequerimientosPlaneacion, "RequerimientosPlaneacion");
